Add TF BPs
finos/compliant-financial-infrastructure pull request #259
Opened 2022-09-07 15:48 UTC by ml4

2022-09-07 16:52 UTC, eddie-knight requested changes

2022-09-07 16:52 UTC, eddie-knight commented on docs/terraform-module-best-practices.md
> +  - Read the [Terraform module documentation]([Terraform Modules](https://www.terraform.io/language/modules)) before attempting to develop one's own child module.
Should be:
```
  - Read the [Terraform module documentation](https://www.terraform.io/language/modules) before attempting to develop one's own child module.
```

2022-09-07 16:53 UTC, eddie-knight commented
@ml4 Looks like you'll need to set up your CLA as an individual or corporate contributor (depending on your employer's policies)

2022-09-07 18:12 UTC, thinkl33t commented
Should the first two sections in this be paragraphs or bulletpoints?

Because the file is markdown, right now the newlines are being stripped and it makes the paragraph a little hard to read.

2022-09-07 19:33 UTC, ml4 commented
Thanks @eddie-knight - weird though I set up my CLA contrib the other day.

2022-09-07 19:41 UTC, ml4 commented
@thinkl33t Thanks - added bullets to Preamble. I imagine most readers will be able to handle the introductory paragraph OK though. Let me know what you think.

2022-09-09 13:23 UTC, thinkl33t approved these changes
LGTM

2022-09-19 15:56 UTC, eddie-knight approved these changes

2022-09-19 15:57 UTC, merged